### ISSUE TITLE
The dependency check scan is not uploading the reports when scanning a project

### ISSUE THREAD

**Issue by ammar-helasoft** [dependency-check/dependency-check-sonar-plugin#859]
**Describe the bug**

The HTML report is not uploaded to the configured sonar.dependencyCheck.htmlReportPath (left to default) on a docker-installed SonarQube with this plugin installed from Marketplace. 

**To Reproduce**
I am running SonarQube in a docker installation (very basic docker setup taken from the [SonarQube project page](https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml) but with https reverse proxy in front of it).

I installed this plugin using Marketplace on SonarQube Admin page and restarted my instance.

I added the Github App, did the entire integration with Github, and got them to work together. I added the Github Action to scan my project (also without changes to the generated Github Action code):

```
name: Build

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
```

When a do a new scan after activating the plugin, no reports are shown and even though I see the tab [Dependency-Check] It is empty with a message saying:

    No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath

**Current behavior**
No reports being uploaded and no traces of logs showing that the Dependency Check is even being performed. Log Levels are set to Debug but still nothing in there.

**Expected behavior**
An html report uploaded to the configured path after each scan.

**Screenshots**

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/70329780/b0b15136-e6f5-49ce-85b9-ddd9073aa70e)

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/70329780/d819e110-db92-41e4-beab-4cb99f352623)

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/70329780/1eb2b6ef-b12f-4787-b8a0-d16f8c44c5cf)

![image](https://github.com/dependency-check/dependency-check-sonar-plugin/assets/70329780/f3b6f312-7504-4ad5-82de-70af2c867aae)

**Versions (please complete the following information):**

-   dependency-check: not sure where to find it.
-   sonarqube: 10.2.1.78527
-   dependency-check-sonar-plugin: 4.0.0

**Additional context**
N/A
